#! /usr/bin/ruby
require 'pp'
require 'etc'
unless File.exist?(File.join Dir.pwd, 'can_write')
  puts "No can_write file found at #{Dir.pwd}"
  exit
end

class Horse
  class << self
    attr_accessor :conf
  end
  @conf = []

  def go!
    self.class.conf.each do |rule|
      rule[:dirs].each do |dir|
        File.chown uid(rule[:user]), gid(rule[:user]), dir if rule[:user] != 'any'
        File.chmod 0777, dir if rule[:access] == :execute
        File.chmod 0666, dir if rule[:access] == :write
        File.chmod 0444, dir if rule[:access] == :read
      end
    end
  end

  def uid name
    Etc.getpwnam(name).uid
  end

  def gid name
    Etc.getpwnam(name).gid
  end
end

class Array
  def should_be_writable
    store_condition :write
  end

  def should_be_readable
    store_condition :read
  end

  def should_be_executable
    store_condition :execute
  end
  
  private 

  def store_condition access
    hash = {:user => 'any', :access => access, :dirs => self}
    Horse.conf << hash
    hash
  end
end

class Hash
  def by_user user
    self[:user] = user
  end
end

at_exit { Horse.new.go! }

load File.join Dir.pwd, 'can_write'
